Repository afes-website/docs, pull requests merged in 2020-10, with the labels that each got.

#153 #152 /online/exhibition/drafts -> /online/drafts
  src/apis/online/drafts/@types.ts
  src/apis/online/drafts/_id@number/accept/index.ts
  src/apis/online/drafts/_id@number/comment/index.ts
  src/apis/online/drafts/_id@number/index.ts
  src/apis/online/drafts/_id@number/publish/index.ts
  src/apis/online/drafts/_id@number/reject/index.ts
  src/apis/online/drafts/index.ts
  src/index.ts
Labels: enhancement

#154 Release v2.2.5
  package.json
Labels: release

#158 #157 image/_id パスを追加
  src/apis/images/_id@string/@types.ts
  src/apis/images/_id@string/index.ts
Labels: bug

#159 #156 DraftParameter を直した
  src/apis/online/drafts/@types.ts
Labels: bug

#160 #155 prepare script を消した
  package.json
Labels: bug

#161 Release v2.2.6
  package.json
Labels: release

#163 #162 image query type - Release v2.2.7
  package.json
  src/apis/images/_id@string/@types.ts
Labels: ASAP, bug

#165 #164 DraftComment.comment -> content | Release v2.2.8
  package.json
  src/apis/online/drafts/@types.ts
Labels: ASAP, improve

#169 #168 Exhibition.content を null-able にしたよ
  src/apis/online/exhibition/@types.ts
Labels: enhancement

#171 #170 フロンティア・ステージ展示対応
  src/apis/online/exhibition/@types.ts
  src/apis/online/exhibition/index.ts
Labels: enhancement

#167 #166 exhibition $post / $patch
  src/apis/online/exhibition/@types.ts
  src/apis/online/exhibition/_id@string/index.ts
  src/apis/online/exhibition/index.ts
Labels: enhancement

#172 Release v2.2.9
  package.json
Labels: release

#174 #173 [Hotfix] 展示IDを変更できないように
  package.json
  src/apis/online/exhibition/@types.ts
  src/apis/online/exhibition/_id@string/index.ts
Labels: ASAP, bug

#176 #175 draft_id を Exhibition に含めた
  src/apis/online/exhibition/@types.ts
Labels: enhancement

#178 Release v2.2.11
  package.json
Labels: release

#182 Room ID を展示オブジェに追加した
  src/apis/online/exhibition/@types.ts
Labels: enhancement

#183 update 2.2.12
  package.json
Labels: release
