Repository afes-website/docs, pull requests merged in 2020-08, with the labels that each got.

#82 #81 管理系アプリ
  swagger.yaml
Labels: ASAP, enhancement, swagger

#84 Feature/#75 user permission
  swagger.yaml
Labels: enhancement

#87 #83 reservationIDを返すように修正
  swagger.yaml
Labels: bug, swagger

#89 #88 reservationObjectにIDを含めた
  swagger.yaml
Labels: bug, swagger

#91 #90 #82で指摘されなかったレビューを諸々修正
  swagger.yaml
Labels: bug, swagger

#95 #93 予約とゲスト間での仕様を統一しました
  src/apis/exh/status/@types.ts
  src/apis/general/guest/@types.ts
  src/apis/general/term/@types.ts
  src/apis/general/term/index.ts
  src/apis/reservation/@types.ts
  src/apis/reservation/auth_email/index.ts
  src/apis/reservation/index.ts
  src/index.ts
Labels: improve

#98 #96 pre commit lint
  package.json
  yarn.lock
Labels: enhancement

#101 Feature/#100 exports
  src/apis/auth/@types.ts
  src/apis/auth/user/index.ts
  src/index.ts
Labels: bug

#108 #107 import ぶっ壊れ事件 修正
  src/apis/blog/articles/@types.ts
  src/apis/blog/revisions/@types.ts
Labels: bug

#112 auth/@types.tsをexport
  src/index.ts
Labels: aspida, bug
