Repository afes-website/docs, pull requests merged in 2020-09, with the labels that each got.

#115 #105 guestおぶじぇくとにしたよん
  src/apis/exh/enter/index.ts
  src/apis/exh/exit/index.ts
  src/apis/general/enter/index.ts
  src/apis/general/exit/index.ts
Labels: bug

#116 term情報をgetした
  src/apis/general/term/index.ts
Labels: bug

#120 #119 invalid reservation info を追加した
  src/apis/general/enter/index.ts
Labels: aspida, improve

#121 Update 2.0.5
  package.json
Labels: release

#126 #125 API 定義を正確に
  src/apis/blog/articles/@types.ts
  src/apis/blog/revisions/@types.ts
  src/apis/blog/revisions/index.ts
Labels: bug

#127 #123 オンライン開催向けのパス追加
  src/apis/auth/@types.ts
  src/apis/online/exhibition/@types.ts
  src/apis/online/exhibition/_id@string/index.ts
  src/apis/online/exhibition/drafts/@types.ts
  src/apis/online/exhibition/drafts/_id@number/accept/index.ts
  src/apis/online/exhibition/drafts/_id@number/comment/index.ts
  src/apis/online/exhibition/drafts/_id@number/index.ts
  src/apis/online/exhibition/drafts/_id@number/publish/index.ts
  src/apis/online/exhibition/drafts/_id@number/reject/index.ts
  src/apis/online/exhibition/drafts/index.ts
  src/apis/online/exhibition/index.ts
  src/apis/onsite/exhibition/enter/index.ts
  src/apis/onsite/exhibition/exit/index.ts
  src/apis/onsite/exhibition/log/index.ts
  src/apis/onsite/exhibition/status/@types.ts
  src/apis/onsite/exhibition/status/_id@string/index.ts
  src/apis/onsite/exhibition/status/index.ts
  src/index.ts
Labels: enhancement

#130 説明文からadminをけした
  src/apis/auth/user/index.ts
Labels: bug

#131 release v2.2.0
  package.json
Labels: release

#133 相対パス厳守運動
  src/apis/online/exhibition/drafts/@types.ts
  src/apis/online/exhibition/drafts/index.ts
Labels: bug

#134 Release v2.2.1
  package.json
Labels: release

#136 #135 package として公開
  .github/workflows/publish.yml
  package.json
Labels: enhancement

#139 #138 created_at を draftCommentに
  src/apis/online/exhibition/drafts/@types.ts
Labels: aspida, enhancement

#137 Release v2.2.2
  package.json
Labels: enhancement

#141 #140 workflow を直した
  .github/workflows/publish.yml
  package.json
Labels: ASAP, bug

#146 #144 add author in draft
  src/apis/online/exhibition/drafts/@types.ts
Labels: enhancement

#150 #148 draft
  src/apis/online/exhibition/drafts/_id@number/index.ts
  src/apis/online/exhibition/drafts/index.ts
Labels: aspida, bug

#149 #148 奇妙な403
  src/apis/online/exhibition/drafts/@types.ts
  src/apis/online/exhibition/drafts/index.ts
Labels: aspida, bug

#151 release v2.2.4
  package.json
Labels: aspida, release
