Repository afes-website/docs, pull requests merged in 2021-04, with the labels that each got.

#233 #222 権限とディレクトリ構造の一新
  package.json
  src/apis/auth/@types.ts
  src/apis/exhibitions/@types.ts
  src/apis/exhibitions/_id@string/index.ts
  src/apis/exhibitions/index.ts
  src/apis/guests/@types.ts
  src/apis/guests/_id@string/check-out/index.ts
  src/apis/guests/_id@string/enter/index.ts
  src/apis/guests/_id@string/exit/index.ts
  src/apis/guests/_id@string/index.ts
  src/apis/guests/check-in/index.ts
  src/apis/guests/index.ts
  src/apis/log/@types.ts
  src/apis/log/index.ts
  src/apis/reservations/@types.ts
  src/apis/reservations/_id@string/check/index.ts
  src/apis/reservations/_id@string/index.ts
  src/apis/reservations/index.ts
  src/apis/reservations/search/index.ts
  src/apis/terms/@types.ts
  src/apis/terms/index.ts
  src/index.ts
Labels: app, enhancement

#238 #257 GUEST_NOT_FOUND の代わりに 404 を返却
  package.json
  src/apis/guests/_id@string/check-out/index.ts
  src/apis/guests/_id@string/enter/index.ts
  src/apis/guests/_id@string/exit/index.ts
Labels: aspida, enhancement

#240 #236 ログ検索クエリから予約 ID を削除
  package.json
  src/apis/log/@types.ts
  src/apis/log/index.ts
Labels: aspida, bug

#241 #239 limit -> capacity
  package.json
  src/apis/exhibitions/@types.ts
  src/apis/guests/_id@string/enter/index.ts
Labels: aspida
