Repository afes-website/docs, pull requests merged in 2021-03, with the labels that each got.

#202 #201 ColorId 型を再定義・term.color_id にも型を付与 [v2.2.19]
  package.json
  src/apis/onsite/general/guest/@types.ts
  src/apis/onsite/general/term/@types.ts
Labels: aspida, bug

#205 #203 Guest Id Prefix に関する諸修正 [v2.2.20]
  package.json
  src/apis/onsite/general/term/@types.ts
Labels: aspida, release

#207 #206 GuestIdPrefix を GuestType に変更 [v2.2.21]
  package.json
  src/apis/onsite/general/term/@types.ts
Labels: aspida

#216 #212･#213 展示が存在しない場合・responseを統一
  package.json
  src/apis/onsite/exhibition/enter/index.ts
  src/apis/onsite/exhibition/exit/index.ts
  src/apis/onsite/exhibition/log/index.ts
  src/apis/onsite/general/exit/index.ts
Labels: aspida, bug, release

#217 fix yaml syntax
  .github/workflows/publish.yml
  package.json
Labels: bug

#218 fix yaml syntax
  .github/workflows/publish.yml
  package.json
Labels: bug

#221 #220 enum を string literal union で置き換えた
  package.json
  src/apis/onsite/general/guest/_id@string/log/@types.ts
Labels: aspida

#224 #199 ⚠ logのエンドポイントを統合+queryを追加
  package.json
  src/apis/onsite/exhibition/log/index.ts
  src/apis/onsite/general/guest/_id@string/log/@types.ts
  src/apis/onsite/general/guest/_id@string/log/index.ts
  src/apis/onsite/general/log/@types.ts
  src/apis/onsite/general/log/index.ts
Labels: aspida, enhancement, onsite

#226 #199-2 export ファイルの修正
  package.json
  src/index.ts
Labels: aspida, bug

#228 #223 名前とサムネIDをonsite展示に追加
  package.json
  src/apis/onsite/exhibition/status/@types.ts
Labels: aspida, enhancement, onsite

#230 v2.3.0
  .eslintrc.js
  .github/workflows/publish.yml
  .github/workflows/test_pull_request.yml
  .prettierignore
  .prettierrc.js
  package.json
  src/apis/onsite/exhibition/enter/index.ts
  src/apis/onsite/exhibition/exit/index.ts
  src/apis/onsite/exhibition/log/index.ts
  src/apis/onsite/exhibition/status/@types.ts
  src/apis/onsite/exhibition/status/_id@string/index.ts
  src/apis/onsite/exhibition/status/index.ts
  src/apis/onsite/general/enter/index.ts
  src/apis/onsite/general/exit/index.ts
  src/apis/onsite/general/guest/@types.ts
  src/apis/onsite/general/guest/_id@string/index.ts
  src/apis/onsite/general/guest/_id@string/log/@types.ts
  src/apis/onsite/general/guest/_id@string/log/index.ts
  src/apis/onsite/general/guest/index.ts
  src/apis/onsite/general/term/@types.ts
  src/apis/onsite/general/term/index.ts
  src/apis/onsite/reservation/@types.ts
  src/apis/onsite/reservation/_id@string/index.ts
  src/apis/onsite/reservation/index.ts
  src/apis/onsite/reservation/search/index.ts
  src/index.ts
  yarn.lock
Labels: aspida, release

#232 blogとonsiteパスを消し飛ばした
  package.json
  src/apis/blog/articles/@types.ts
  src/apis/blog/articles/_id@string/bad/index.ts
  src/apis/blog/articles/_id@string/good/index.ts
  src/apis/blog/articles/_id@string/index.ts
  src/apis/blog/articles/index.ts
  src/apis/blog/categories/@types.ts
  src/apis/blog/categories/index.ts
  src/apis/blog/revisions/@types.ts
  src/apis/blog/revisions/_id@number/accept/index.ts
  src/apis/blog/revisions/_id@number/index.ts
  src/apis/blog/revisions/_id@number/reject/index.ts
  src/apis/blog/revisions/contrib/@types.ts
  src/apis/blog/revisions/contrib/index.ts
  src/apis/blog/revisions/index.ts
  src/apis/online/drafts/@types.ts
  src/apis/online/drafts/_id@number/accept/index.ts
  src/apis/online/drafts/_id@number/comment/index.ts
  src/apis/online/drafts/_id@number/index.ts
  src/apis/online/drafts/_id@number/publish/index.ts
  src/apis/online/drafts/_id@number/reject/index.ts
  src/apis/online/drafts/index.ts
  src/apis/online/exhibition/@types.ts
  src/apis/online/exhibition/_id@string/index.ts
  src/apis/online/exhibition/index.ts
  src/index.ts
Labels: aspida
