Repository afes-website/docs, pull requests merged in 2021-11, with the labels that each got.

#315 #314 github.base_ref を使うようにした
  .github/workflows/test_pull_request.yml
Labels: bug, skip-version

#313 #312 rsv/_id/check を executive 権限でも叩けるように
  package.json
  src/apis/reservations/_id@string/check/index.ts
Labels: enhancement

#294 #287 [v3.4.0] bulk update を追加
  package.json
  src/apis/guests/bulk-update/@types.ts
  src/apis/guests/bulk-update/index.ts
  src/apis/log/@types.ts
  src/index.ts
Labels: enhancement, aspida
