Repository afes-website/docs, pull requests merged in 2021-09, with the labels that each got.

#275 #274 [v3.2.0] /reservations/_id/check の認証を外す
  package.json
  src/apis/reservations/_id@string/check/index.ts
Labels: enhancement, aspida

#277 #276 404 の時のエラーコードを定義
  src/apis/auth/users/_id@string/change_password/index.ts
  src/apis/auth/users/_id@string/index.ts
  src/apis/auth/users/_id@string/regenerate/index.ts
  src/apis/exhibitions/_id@string/index.ts
  src/apis/guests/_id@string/check-out/index.ts
  src/apis/guests/_id@string/enter/index.ts
  src/apis/guests/_id@string/exit/index.ts
  src/apis/images/_id@string/index.ts
  src/apis/reservations/_id@string/check/index.ts
  src/apis/reservations/_id@string/index.ts
Labels: enhancement

#278 release v3.3.0-alpha.1
  package.json
Labels: release

#280 #279 INVALID_RESERVATION_INFO を削除
  src/apis/guests/check-in/index.ts
  src/apis/reservations/_id@string/check/index.ts
Labels: improve, aspida
