Repository afes-website/docs, pull requests merged in 2021-02, with the labels that each got.

#185 #184 add MIT LICENSE
  LICENSE
  package.json
Labels: discuss

#186 Release 2.2.13
  package.json
Labels: release

#188 #187 check pathを生成
  src/apis/onsite/exhibition/enter/index.ts
  src/apis/onsite/exhibition/exit/index.ts
  src/apis/onsite/general/enter/index.ts
  src/apis/onsite/reservation/_id@string/check/index.ts
Labels: aspida, enhancement

#189 update v2.2.14
  package.json
Labels: aspida

#191 #190 reserv/check の権限拡張
  package.json
  src/apis/onsite/reservation/_id@string/check/index.ts
Labels: aspida, improve

#195 #193 duplicate license
  package.json
Labels: aspida, bug

#193 #192 status_codeをnullableにした
  package.json
  src/apis/onsite/reservation/_id@string/check/index.ts
Labels: aspida, bug

#197 #196 termの条件を追記
  package.json
  src/apis/onsite/exhibition/status/@types.ts
Labels: aspida, improve, onsite

#200 #198 exh/generalが(他の)展示情報を見れるように
  src/apis/onsite/exhibition/status/_id@string/index.ts
  src/apis/onsite/exhibition/status/index.ts
Labels: aspida, enhancement
