Repository afes-website/docs, pull requests merged in 2021-10, with the labels that each got.

#284 #283 エラーコードを CHECKED_IN, CHECKED_OUT に統一
  package.json
  src/apis/guests/_id@string/check-out/index.ts
  src/apis/guests/_id@string/enter/index.ts
  src/apis/guests/_id@string/exit/index.ts
  src/apis/reservations/_id@string/check/index.ts
Labels: enhancement

#286 #285 生徒がチェックアウトできないようにする
  src/apis/guests/_id@string/check-out/index.ts
  src/apis/terms/@types.ts
Labels: enhancement

#292 #291 ALL_MEMBER_CHECKED_IN を使う
  package.json
  src/apis/reservations/_id@string/check/index.ts
Labels: bug, aspida

#309 Release v3.3.3 to dev
  package.json
Labels: release

#308 Release v3.3.3
  package.json
  src/apis/reservations/_id@string/check/index.ts
  src/apis/reservations/_id@string/index.ts
  src/apis/terms/@types.ts
Labels: release

#311 #310 バージョン差分を CI で確認
  .github/workflows/test_pull_request.yml
Labels: skip-version
